### ISSUE TITLE
Release new Version on Puppet Forge

### ISSUE THREAD

**Issue by marcelfischer** [voxpupuli/puppet-mlocate#27]
## What are you seeing
On https://forge.puppet.com/modules/puppet/mlocate the latest release is from Feb 14th 2020
If you for example use the newest puppet-systemd module, this breaks your puppet run.

## What behaviour did you expect instead
Release a new version with latests commits

Thank you for your awesome work!

**Comment by traylenator** [comment]
Sure thing.
